name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package dataset
        run: tar -czf gcb-dataset.tar.gz .